name = "accurate-shop"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "accurate-db"
database_id = "YOUR_DATABASE_ID"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'accurate-media'

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_ID"
